### ISSUE TITLE
10/4 Discussion

### ISSUE THREAD

**Issue by SanyaSriv** [lkuper/CSE232-2023-09#1]
Scribe for Group 6: @pskillam8 (Paul Killam)

**Comment by ZackJorquera** [comment]
Scribe for Group 5: @stevenkordonowy (Steven Kordonowy)

**Comment by Sanjana-Patil22** [comment]
Scribe for Group 1: @mavrogiannakisap (Apostolos Mavrogiannakis)

**Comment by LikithRahul** [comment]
Scribe for Group 3: @TylerMorton

**Comment by eyab** [comment]
Scribe for Group 4: @xiwen426(Xi Wen)

**Comment by pskillam8** [comment]
Hi all, Tyler and I have started working on a doc here:
https://hackmd.io/@TylerMorton/By993zk-a/edit
With more info in Zulip.

Open TODOs: 
1. Make sure everyone's notes are included, and all sides of the conversation had in class are represented
2. Assign a head-scribe/editor to make sure the doc reads with a common voice/writing style

**Comment by lkuper** [comment]
@ImpregnableProgrammer Tagging you since you're a scribe from 10/4.  Now all the scribes from last time have been tagged.  Talk amongst yourselves!

**Comment by pskillam8** [comment]
I can take on the head scribe role to make sure everything flows.  

Other scribes, please go through the already written notes (linked above) and confirm that they are representative of the notes from your group.

@ImpregnableProgrammer @xiwen426 @TylerMorton @mavrogiannakisap @stevenkordonowy 

Also can someone take care of transcribing the notes over to the wiki once they're finalized?

**Comment by pskillam8** [comment]
Hi @lkuper , our draft summary is ready for review:
https://hackmd.io/uO2J0iR_TvWQ_pGwZ3-pPA?view

**Comment by TylerMorton** [comment]
I'm not sure about the process to go about the wiki so I just pushed the draft @pskillam8.

**Comment by lkuper** [comment]
Thanks, all!  I'll grade this on Canvas shortly.  For context, the due date on http://decomposition.al/CSE232-2023-09/schedule.html ("11:59:59pm PT on 10/11") is the date the writeup is due, not the date by which to request feedback to be incorporated into the final version.  I am more than happy to give feedback before the due date, but I need a lot more than two hours of lead time -- it would need to be a couple of days, at least.

**Comment by lkuper** [comment]
Grades and comments posted on Canvas.  (Sorry this took a while.)
