### ISSUE TITLE
10/9 Discussion

### ISSUE THREAD

**Issue by Jake-C-S** [lkuper/CSE232-2023-09#2]

**Comment by Head-inthe-Cloud** [comment]
Scribe for Group 5: @kweenkeen (Jack Fox Keen)

**Comment by Jake-C-S** [comment]
Scribe for Group 2: @pskillam8 (Paul Killam)

**Comment by jp0utside** [comment]
Scribe for Group 4: @mavrogiannakisap Apostolos Mavrogiannakis

**Comment by rohan527** [comment]
Scribe for Group 1: @nsampat1  (Nithyasree Sampath)

**Comment by lkuper** [comment]
Tagging in @eyab and ~~@ArberSephirotheca~~ @zw615.  That should be all the scribes for 10/9.  (Edit

If y'all want to get feedback on a draft before it's due (Monday at 11:59:59pm), you should get the wiki updated with the draft today.  I'm unlikely to have time to give feedback over the weekend or on Monday.

**Comment by ArberSephirotheca** [comment]
> Tagging in @eyab and @ArberSephirotheca. That should be all the scribes for 10/9.
> 
> If y'all want to get feedback on a draft before it's due (Monday at 11:59:59pm), you should get the wiki updated with the draft today. I'm unlikely to have time to give feedback over the weekend or on Monday.

Sorry, but I don't think I am the scribe for 10/9 Group 3, it should be Zeyu Wang

**Comment by lkuper** [comment]
@ArberSephirotheca Oops, my mistake! Tagging in @zw615 (Zeyu Wang).

**Comment by zw615** [comment]
Done updating the github wiki page based on [hackmd](https://hackmd.io/@0r9HBl_DS5Cu9qZfSMt27w/HJRBkVPbp/edit)

**Comment by lkuper** [comment]
Grades and comments posted on Canvas.
