### ISSUE TITLE
10/13 Discussion

### ISSUE THREAD

**Issue by LikithRahul** [lkuper/CSE232-2023-09#4]

**Comment by LikithRahul** [comment]
Scribe for group 4: @ArberSephirotheca

**Comment by eyab** [comment]
Scribe for group 2: Cheng-Wei Ching
@cwching-ucsc

**Comment by kajalp1929** [comment]
Scribe for group 3 : Manasi Pawar
@pawar-manasi

**Comment by jlortiz0** [comment]
Scribe notes from the [hackmd](https://hackmd.io/N4N0K_XHQQqrZrQ-exYIrQ?both) have been uploaded.

**Comment by lkuper** [comment]
Grades and comments posted on Canvas.
