### ISSUE TITLE
10/18 Discussion

### ISSUE THREAD

**Issue by ssfaruqu** [lkuper/CSE232-2023-09#5]
Group 5 scribe: Ehsan Mirafzali, @VargEM

**Comment by SanyaSriv** [comment]
Scribe for Group 4: Rithik Sharma (@SharmaRithik)

**Comment by TylerMorton** [comment]
Scribe 👏 for 👏 Group 👏 3 👏 : Yunqian Cheng (@Head-inthe-Cloud 😶‍🌫️)

**Comment by TheFllood** [comment]
Scribe for Group 1: Yinzhe Zahng (@HigashikataZhangsuke)

**Comment by lkuper** [comment]
Grades and comments posted on Canvas.
