### ISSUE TITLE
10/23 Discussion

### ISSUE THREAD

**Issue by SharmaRithik** [lkuper/CSE232-2023-09#6]

**Comment by SharmaRithik** [comment]
Scribe for Group 1: Muhammad Hamza Shahzad(@hamzashahzad1)

**Comment by obhalera** [comment]
Scribe for Group 4: Ehsan Mirafzali(@VargEM)

**Comment by nsampat1** [comment]
Scribe for Group 5: Apostolos Mavrogiannakis(@mavrogiannakisap)

**Comment by lkuper** [comment]
Grades and comments posted on Canvas.
